# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'kwConsumerMobile' do
  rn_maps_path = '../node_modules/react-native-maps'

  pod 'React',
    :path => "../node_modules/react-native",
    :subspecs => [
      'Core',
      'CxxBridge',
      'DevSupport',
      'RCTActionSheet',
      'RCTAnimation',
      'RCTGeolocation',
      'RCTImage',
      'RCTLinkingIOS',
      'RCTNetwork',
      'RCTSettings',
      'RCTText',
      'RCTVibration',
      'RCTWebSocket',
      ]

  pod 'yoga',
    :path => "../node_modules/react-native/ReactCommon/yoga"

  pod 'DoubleConversion',
    :podspec => "../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec",
    :inhibit_warnings => true

  pod 'Folly',
    :podspec => "../node_modules/react-native/third-party-podspecs/Folly.podspec",
    :inhibit_warnings => true

  pod 'glog',
    :podspec => "../node_modules/react-native/third-party-podspecs/glog.podspec",
    :inhibit_warnings => true

  pod 'react-native-maps', :path => rn_maps_path

  pod 'RNVectorIcons',
    :path => '../node_modules/react-native-vector-icons'

  pod 'react-native-google-maps', path: rn_maps_path
  pod 'GoogleMaps'
  pod 'Google-Maps-iOS-Utils'

  # pod 'Firebase/Core'

  # pod 'RNFirebase',
  #     :path => '../node_modules/react-native-firebase/ios'

  post_install do |installer|
    installer.pods_project.main_group.tab_width = '2';
    installer.pods_project.main_group.indent_width = '2';

    installer.pod_targets.each do |target|

      if target.name == 'react-native-google-maps'
        target.native_target.build_configurations.each do |config|
          config.build_settings['CLANG_ENABLE_MODULES'] = 'No'
        end
      end

      if target.pod_name == 'AppAuth'
        target.native_target.build_configurations.each do |config|
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
        end
      end
      # Build React Native with RCT_DEV enabled
      next unless target.pod_name == 'React'
      target.native_target.build_configurations.each do |config|
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'RCT_DEV=1'
      end

    end
  end
end
